/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javamariadbconnectiontest;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class App {
    public static void main(String[] args) {
        String query = "";
        String jdbcUrl = "jdbc:mariadb://localhost:3306/mysql" + query;
        String username = "root";
        String password = "example";
        Connection connection = null;
        try {
            connection = DriverManager.getConnection(jdbcUrl, username, password);
            System.out.println("Connected to the MariaDB server successfully.");
        } catch (SQLException e) {
            System.out.println("An error occurred while connecting to the MariaDB server.");
            e.printStackTrace();
        } finally {
            try {
                if (connection != null) {
                    connection.close();
                }
            } catch (SQLException e) {
                System.out.println("An error occurred while closing the connection.");
                e.printStackTrace();
            }
        }
    }
}
