# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    # volumes:
    #   - ./db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080